# -*- coding: utf-8 -*-
"""27_04_ML_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5nTWDYgAFA7W8-nrcZEk3eke6EAnFpq
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

# Veri Oluşturma

X, y = make_classification(n_samples = 100, n_features=1, n_informative=1, n_redundant=0, n_classes = 2,n_clusters_per_class=1, random_state=42)

# Lojistic Regresyon modeli oluşturma ve eğitme

clf = LogisticRegression()
clf.fit(X,y)
# Karar Sınırı Oluşturma
x_values =np.linspace(-3,3,100) # -3 ve 3 arasında lineer olarak eşit aralıklı 100 değer
y_values = clf.predict_proba(x_values.reshape(-1,1))[:,1]
# predict_proba()= her x değeri için her sınıfın olasılığını verir
# biz sadece + sınıfın olasılıklarını kullanıyoruz. [:,1]
# reshape(-1,1) =n predict_proba() metodu bizden tek bir dizi halinde veri ister.

# Veriyi Görselleştirme
plt.figure(figsize=(8,6))
plt.scatter(X,y,color='b',marker='o',label= "Veri Noktaları")
plt.plot(x_values,y_values,color='r', label="Lojistik Regresyon Modeli")
plt.xlabel("Özellikler")
plt.ylabel("Sınıflar")
plt.title("LogReg Örneği")
plt.legend()
plt.grid(True)
plt.show()

